### ISSUE TITLE
Last pr closed was 23 aug 2023,  anyone maintaining this repo?

### ISSUE THREAD

**Issue by jacobbogers** [rollup/awesome#127]
23 aug 2023 was the last pr closed....anyone maintaining the repo?

**Comment by shellscape** [comment]
yep, but we could always use help. rollup has two primary maintainers and we're stretched thin.

**Comment by jacobbogers** [comment]
I would gladly help out, I can work on this specific repo, I can collect all the submissions for awesome and process them on a weekly basis, would that work for you?

**Comment by shellscape** [comment]
OK cool. Any cadence is fine by me. I'll send you an invite. All we ask is that you consider the contributing guide in all submissions.

**Comment by jacobbogers** [comment]
I have not yet received your invite)), could i checked my gmail, thoroughly,  you can also send it jkfbogers@protonmail.com

> OK cool. Any cadence is fine by me. I'll send you an invite. All we ask is that you consider the contributing guide in all submissions. Thanks for volunteering your time!

**Comment by shellscape** [comment]
@jacobbogers we sent you an invite but it was never accepted 
![Screenshot_20240505_232024_Brave](https://github.com/rollup/awesome/assets/76371/71cdabdf-30d7-4edc-bd35-05ea296985f8)

We'll send another but I suggest checking your spam and filters.

**Comment by jacobbogers** [comment]
Hello, just decided to circle back and see whats up, yes I found the issue I have 2 emails on github and the one noticed as my "primary" does not exist anymore, I have updated my settings, so if you send an invite it should be ok
