### ISSUE TITLE
Deprecate rollup-plugin-babel-minify

### ISSUE THREAD

**Issue by dilyanpalauzov** [rollup/awesome#63]
As of https://github.com/Comandeer/rollup-plugin-babel-minify `rollup-plugin-babel-minify` is deprecated and dead.

Update https://github.com/rollup/awesome#output the babel-minify line to state, that `rollup-plugin-terser` shall be preferred over `rollup-plugin-babel-minify`.

**Comment by shellscape** [comment]
You're welcome to submit a PR with that fix. We rely upon the community to curate this list.
